comment: false
codecov:
  branch: main
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
flag_management:
  default_rules: # the rules that will be followed for any flag added, generally.
    carryforward: true
